### PR TITLE
don't overwrite property if data is null or undefined

### PR DESCRIPTION
**Pull request by superMDguy**
This fixes a case I have where a property is provided either as an `@Input` or as a route param depending on where it's used.

### CODE REVIEW

**Comment by scaljeri** [comment]
Interesting, does this mean you do something like this

```@Input() @RouteData({observable: false}) foo;```

I need some time to think this one over. Although I see why you need this, I'm not sure yet if it is correct RouteData behaviour

**Comment by superMDguy** [comment]
> does this mean you do something like this

Yes, that's the idea. There's no rush, though, so feel free to think about it as long as you need to.

**Comment by scaljeri** [comment]
An alternative solution might be to have a `filter` and `map` option added to the RouteXxlConfig, like I've done in this [stackblitz]( https://stackblitz.com/edit/angular-route-xxl-filter?file=app%2Ffoo-bar-inherit%2Ffoo-bar-inherit.component.ts). 

```@RouteQueryParams('x', { inherit: true, filter: ignoreValue, map: mapValue }) x$;```
In the stackblitz I update the queryparam `x` each second and filter out the value `x === 10`

This will also solve your issue. I don't think it is good to ignore `undefined/null`. For example, if the url changes from 

```http://example.com?x=10```

to

```http://example.com```

You want

```@RouteQuerParams() x$;```

to go from `10` to `null`. That is, under normal conditions a valid and useful change.

**Comment by superMDguy** [comment]
Ok, that makes sense. Do you plan directly adding it based on your stackblitz, or do you want me to work on it?

**Comment by scaljeri** [comment]
If you have time to do it, it would be great! Note that I've added `stryker`, it might help with writing unit test!

**Comment by scaljeri** [comment]
I would like to merge `filter` and `map`

```
if (item.config.filter) {
    stream$ = stream$.pipe(item.config.filter);
}
if(item.config.map) {
    stream$ = stream$.pipe(item.config.map);
}
```

into a single property, because they are basically identical. So, instead of doing

```@RouteData({filter: filerValue, map: mapValue) val$;```

do

```@RouteData({pipe: [filerValue, mapValue]}) val$;```

or if a single property

```@RouteData({pip: filerValue}) val$;```

Right now I cannot think of a better name than `pipe`.

**Comment by superMDguy** [comment]
Ok, sounds good. I'll have time to work on it during the week.

**Comment by superMDguy** [comment]
I think I prefer having filter and map separate. If users want to have only a `map`, but no `filter`, they'd have to have `pipe: [null, mapValue]`, which is kind of awkward.

**Comment by scaljeri** [comment]
Thats not how it works, you can do

    pipe: [mapValue]
    pipe: [filterValue]
    pipe: [mapValue, filterValue]

The way you implement this is as follows:

     stream$ = stream$.pipe(...item.config.pipe);

Note that

    pipe: [mapValue, filterValue]

can have a different outcome then

    pipe: [filterValue, mapValue]

**Comment by scaljeri** [comment]
I've spend some time thinking about your example

    @Input() @RouteData({observable: false}) foo;

Although I don't know the context, but shouldn't you move the `@RouteData` to the parent component and just provide the value to this component.  The parent component can decide if he wants to use the value from `@RouteData` or one from an other source.

**Comment by scaljeri** [comment]
Hi Matthew, any progress on this PR? I really like this feature so I would like to merge it :) If time is not on your side these days, I can complete it for you if you like?

**Comment by superMDguy** [comment]
Sorry, I haven't had time to work on it. If you could complete it, that'd be great.

**Comment by scaljeri** [comment]
I've create a new PR based on your code and just merged it

**Comment by scaljeri** [comment]
I've just released v1.5.0 which has the `pipe` option. Please let me know if it doesn't do what you need!

**Pull request closed without merging**
